### ISSUE TITLE
Red & green are standard, but not great for colorblind people

### ISSUE THREAD

**Issue by ProfessorO** [dakotacookenmaster/cptr-108-digital-logic-simulator-lab#4]
The default red = 0 = off and green = 1 = on are pretty standard. And the connection nodes show 0 or 1, so it can still be read without relying on the colors. However, red/green colorblindness is a reality for about 8% of Caucasian men, and many others, so it would be good to consider other alternatives.

**Comment by dakotacookenmaster** [comment]
Hm, perhaps we could have a colorblind mode toggle, that allows users to change the theme? This wouldn't be too bad, because we can configure a default theme and utilize it, and then update the display dynamically when the toggle is checked.

**Comment by dakotacookenmaster** [comment]
Fixed in `1.5.0`. Based on this article (https://www.datylon.com/blog/data-visualization-for-colorblind-readers#what-colors-can-they-see), I opted to use blue as the "on" color, and red as the "off" color. By also using a "second encoding" (i.e., the numbers 0 for off and 1 for on), this should hopefully help those who have colorblindness to better use the app.
