### ISSUE TITLE
Click to place new gate

### ISSUE THREAD

**Issue by ProfessorO** [dakotacookenmaster/cptr-108-digital-logic-simulator-lab#8]
I've occasionally "lost" a new gate (or mistakenly added several) because the new tiles always show up in the same place. What do you think of a click-to-place process instead, where you click on the gate you want, and then click again where you want it to show up? In this case, it would help if the selected gate remained highlighted in the menu on the left until it was placed.

Another possibility would be to drag (a clone of) the gate from the palette on the left. That might be more complicated, both to implement and to use--I'm not sure. I'd like to hear your thoughts on this, though.

**Comment by dakotacookenmaster** [comment]
@ProfessorO I do like the idea of click-to-place, this seems like the option we'll end up going with if we change this. I agree that it's pretty easy to lose gates you insert because they all get placed in the same location on initialization. I had attempted to do a row- / column-based system at first, but that proved to be problematic.

The idea of dragging the items is cool, but would be extremely challenging to implement on mobile devices. So in the case that we do update the system to support a replacement means of placement, I'd choose the first approach.

**Comment by dakotacookenmaster** [comment]
Implemented in `1.3.1`.
