### ISSUE TITLE
7-segment display input names

### ISSUE THREAD

**Issue by ProfessorO** [dakotacookenmaster/cptr-108-digital-logic-simulator-lab#9]
On the 7-segment display, it's a bit odd that input 0 is the 8s place, input 1 is the 4s place, etc. It would be nice if the inputs were either numbered from least to most significant (input 0 = 1, input 1 = 2, input 2 = 4, input 3 = 8, so the input number is the power 2 is raised to), or actually had their place values (i.e., named something like 1s place, 2s place, 4s place, 8s place).

**Comment by dakotacookenmaster** [comment]
The reason for this is that the inputs are placed "top down". That is, pin 0 is the "top-most" pin. This is due to the loop used to render the pins. I'm not opposed to changing the ordering of the pins, but if you assumed that the display was turned 90 degrees counter-clockwise, those would be the positions of the bits.

I like the second option, where inputs actually have optional names associated with them. This would be especially helpful when building something like a latch, where the input / output have specific meaning (i.e., SET / RESET).

**Comment by ProfessorO** [comment]
That makes sense. It might be fairly straightforward to make inputs #0 map to the 1s place instead of the 8s place as an intermediate step, and then move on to full input names (eventually).

**Comment by dakotacookenmaster** [comment]
This has been fixed in version `1.2.3`. 7-segment displays now tell you which input you're connecting to with an appropriate label.
